backend:
  name: git-gateway
  branch: main
publish_mode: editorial_workflow
media_folder: "imgs/uploads"
collections:
  - name: "categories"
    label: "Categories"
    folder: "content/categories"
    slug: "{{slug}}"
    editor:
      preview: false
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Icon image", name: "icon", widget: "image" }
