backend:
  name: git-gateway
  branch: main
media_folder: "public/imgs/uploads"
public_folder: "/imgs/uploads"
collections:
  - name: "categories"
    label: "Categories"
    folder: "content/categories"
    slug: "{{fields.categoryId}}"
    editor:
      preview: false
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Category ID",
          name: "categoryId",
          widget: "string",
          hint: "Please set an unique id for this category. Do not input blank spaces.",
        }
      - { label: "Icon image", name: "icon", widget: "image" }
      - {
          label: "Show on home page",
          name: "showOnHome",
          widget: "boolean",
          default: false,
        }
  - name: "products"
    label: "Products"
    folder: "content/products"
    slug: "{{slug}}"
    editor:
      preview: false
    create: true
    format: "json"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Product ID", name: "id", widget: "string" }
      - { label: "Product image", name: "thumbnail", widget: "image" }
      - {
          label: "Category",
          name: "category",
          widget: "relation",
          collection: "categories",
          search_fields: ["title", "categoryId"],
          value_field: "categoryId",
          display_fields: ["title"],
        }
      - label: "Attributes"
        name: "attributes"
        widget: "object"
        fields:
          - { label: "Envelope Size", name: "envelopeSize", widget: "string" }
          - { label: "Adhesion Type", name: "adhesionType", widget: "string" }
          - { label: "Window Style", name: "windowStyle", widget: "string" }
          - { label: "Compatibility", name: "compatibility", widget: "string" }
          - {
              label: "Security Tint",
              name: "hasSecurityTint",
              widget: "boolean",
              default: false,
            }
          - { label: "Features", name: "features", widget: "string" }
          - { label: "Additional", name: "additional", widget: "string" }
